name: Remove unintended public image
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  remove:
    runs-on: ubuntu-24.04
    steps:
      - name: Remove the newly created package containing only the unintended version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api --method DELETE orgs/genropy/packages/container/gramlot-rosetta
